{$resource '.\Data\Assets.RES'}

{$resource '.\Data\Misc.RES'}

{$resource '.\Data\Cursors.RES'}
{$resource '.\Data\Particles.RES'}
{$resource '.\Data\Sounds.RES'}

{$resource '.\Data\Custom.RES'}

{$resource '.\Data\orig.RES'}
{$resource '.\Data\ohno.RES'}
{$resource '.\Data\h94.RES'}
{$resource '.\Data\x91.RES'}
{$resource '.\Data\x92.RES'}

{$resource '.\Data\orig_music.RES'}
{$resource '.\Data\ohno_music.RES'}
{$resource '.\Data\h94_music.RES'}












